Version selection for grade calculator
fsphys-muenster/homepage-php pull request #4
Opened 2021-04-12 09:06 UTC by APN-Pucky

Some testing is still necessary.

2021-04-20 15:26 UTC, 2xB requested changes
Vielen Dank für die ganzen Änderungen! Mir sind nur wenige Sachen aufgefallen:

 * Mehrsprachigkeit fehlt (vmtl. auch, weil die Testseite bis gerade eben keine Mehrsprachigkeit unterstützt hat)
 * Das Änderungsdatum des Notenrechner-Scriptes ist verschwunden (im Code an den entsprechenden Stellen angemerkt)
 * Das Note in der URL speichern-Feature via Button am Ende der Seite müsste noch auf die Änderungen angepasst werden
 * Mancher Code ist auskommentiert, evtl. wäre es sinnvoll, den einfach zu löschen?

2021-04-20 15:26 UTC, 2xB commented on www/data/Physik.FSPHYS/imperialive/Physik.FSPHYS/studieren/notenrechner_snippet_de.html
> -<p><small>Version: <span id="fsphys_gc_version">2016-11-17</span>, <abbr title="Prüfungsordnung">PO</abbr>-Version: Ab <span id="fsphys_gc_er_version">WS 2016/2017</span></small></p>
Das span `fsphys_gc_version` war dafür da, anzugeben, wann der Notenrechner zuletzt geändert wurde. Ich würde es deshalb auch weiterhin als Info da lassen. Dass da ein konkretes Datum steht, muss nicht sein, weil das Datum im JavaScript auch nochmal aktualisiert wird.

2021-04-20 16:25 UTC, APN-Pucky commented on www/data/Physik.FSPHYS/imperialive/Physik.FSPHYS/studieren/notenrechner_snippet_de.html
> -<p><small>Version: <span id="fsphys_gc_version">2016-11-17</span>, <abbr title="Prüfungsordnung">PO</abbr>-Version: Ab <span id="fsphys_gc_er_version">WS 2016/2017</span></small></p>
Ok, ich dachte an eine Version/Datum pro Prüfungsordnung. Aber eine globale Version kann ja zusätzlich nicht schaden.

2021-04-20 16:46 UTC, 2xB commented on www/data/Physik.FSPHYS/imperialive/Physik.FSPHYS/studieren/notenrechner_snippet_de.html
> -<p><small>Version: <span id="fsphys_gc_version">2016-11-17</span>, <abbr title="Prüfungsordnung">PO</abbr>-Version: Ab <span id="fsphys_gc_er_version">WS 2016/2017</span></small></p>
Ja, das Datum der Prüfungsordnung ist `fsphys_gc_er_version`, das Datum der letzten Notenrechner-Änderung ist `fsphys_gc_version`. Theoretisch könnte man letzteres natürlich auch rausnehmen, aber vielleicht ist es auch praktisch, zu wissen, ob sich am Notenrechner in der Zwischenzeit was geändert hat. Ich wollte es nur angemerkt haben, mach damit, was du möchtest!

2021-05-27 20:36 UTC, APN-Pucky commented
Jetzt sollte sowohl die Englische Seite, also auch das Speichern mit PO-Version klappen.

2021-06-16 18:48 UTC, merged